# Generated by Django 3.0.6 on 2020-05-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ingredient_price', models.IntegerField()),
                ('ingredient_calval', models.IntegerField()),
                ('ingredient_category', models.CharField(choices=[('FR', 'Fruits'), ('NU', 'Nuts'), ('FL', 'Flakes'), ('SE', 'Seeds'), ('OT', 'Other')], max_length=2)),
            ],
        ),
    ]
