# Generated by Django 3.0.6 on 2020-05-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ingredient')),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mix')),
            ],
        ),
        migrations.AddField(
            model_name='mix',
            name='ingredients',
            field=models.ManyToManyField(through='main.Percentage', to='main.Ingredient'),
        ),
    ]
