# Generated by Django 3.0.6 on 2020-05-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='percentage',
            old_name='mix',
            new_name='recipe',
        ),
    ]
