# Generated by Django 3.0.6 on 2020-06-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200528_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Percentage',
            new_name='Quantity',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='percentage',
            new_name='quantity',
        ),
    ]
