# Generated by Django 3.0.6 on 2020-06-15 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200615_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_posted',
            field=models.DateField(default=datetime.datetime(2020, 6, 15, 18, 52, 4, 672762), verbose_name='date published'),
        ),
    ]
