# Generated by Django 3.0.6 on 2020-05-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200513_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_slug',
            field=models.CharField(default='oatflakes', max_length=200),
            preserve_default=False,
        ),
    ]
