# Generated by Django 3.0.6 on 2020-05-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ingredient_ingredient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_image_src',
            field=models.CharField(default='main/<django.db.models.fields.CharField>', max_length=255),
        ),
    ]
