# Generated by Django 3.0.6 on 2020-06-15 20:32

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200615_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=main.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_posted',
            field=models.DateField(default=datetime.datetime(2020, 6, 15, 22, 32, 14, 721909), verbose_name='date published'),
        ),
    ]
