# Generated by Django 3.0.6 on 2020-05-18 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_ingredient_ingredient_image_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentage',
            name='mass',
        ),
        migrations.AddField(
            model_name='mix',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='percentage',
            name='percentage',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_image_src',
            field=models.CharField(default='main/REPLACE.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
