# Generated by Django 3.0.6 on 2020-05-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200518_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='total_carbs',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='total_fat',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='total_proteins',
            field=models.FloatField(default=11),
            preserve_default=False,
        ),
    ]
