# Generated by Django 3.0.6 on 2020-06-18 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200617_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories_per_serving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_posted',
            field=models.DateField(default=datetime.datetime(2020, 6, 18, 18, 30, 45, 321327), verbose_name='date published'),
        ),
    ]
