# Generated by Django 3.0.6 on 2020-06-19 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200618_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_posted',
            field=models.DateField(default=datetime.datetime(2020, 6, 19, 7, 38, 33, 958343), verbose_name='date published'),
        ),
    ]
