# Generated by Django 3.0.6 on 2020-06-19 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200619_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_posted',
            field=models.DateField(default=datetime.datetime(2020, 6, 19, 8, 41, 26, 644657), verbose_name='date published'),
        ),
    ]
