# Generated by Django 3.0.6 on 2020-06-19 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200619_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_posted',
            field=models.DateField(default=datetime.datetime(2020, 6, 19, 8, 43, 11, 196939), verbose_name='date published'),
        ),
    ]
