# Generated by Django 3.0.6 on 2020-06-19 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200619_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_posted',
            field=models.DateField(default=datetime.datetime(2020, 6, 19, 19, 47, 23, 408469), verbose_name='date published'),
        ),
    ]
