# Generated by Django 3.0.6 on 2020-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200619_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='price_per_serving',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=7),
            preserve_default=False,
        ),
    ]
