# Generated by Django 3.0.6 on 2020-06-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_recipe_price_per_serving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='category_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
