# Generated by Django 3.0.6 on 2020-06-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200622_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategory',
            old_name='category_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='foodcategory',
            old_name='category_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='foodcategory',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='foodcategory',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_calval',
            new_name='calval',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='total_carbs',
            field=models.FloatField(),
        ),
    ]
