# Generated by Django 3.0.9 on 2020-08-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name_plural': 'Quantities'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredient_image_src',
        ),
    ]
