# Generated by Django 3.0.9 on 2020-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200811_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
